### ISSUE TITLE
Please don't use Array().fill !!

### ISSUE THREAD

**Issue by etpinard** [dfcreative/regl-line2d#29]
... or make sure it is transpiled. 

See:

https://github.com/dfcreative/regl-line2d/blob/master/index.js#L563

and possibly elsewhere.

----

Non-ES5 statements like this one makes our (very) old image test server crash.

**Comment by dfcreative** [comment]
Done, thank you @etpinard!

**Comment by etpinard** [comment]
Wow. That was fast :tada: 

Big thanks!
